target ‘Ofoimtage’ do
platform :ios, '9.0'
pod 'Masonry', '~> 1.0.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDCycleScrollView', '~> 1.65'
pod 'YYModel'
#pod 'AMap3DMap' #3D地图SDK #
pod 'AMap2DMap' #2D地图SDK (2D和3D不能同时使用)
pod 'AMapSearch'
end
